data:
  raw_dir: "data/raw/visDrone.v5-visdrone_rcnn.coco"
  processed_dir: "data/processed"
  model_save_dir: "models_weights"
  train_split: "train"
  valid_split: "valid"
  test_split: "test"
  batch_size: 16
  num_classes: 10
  img_size: 640
  seed: 42

yolo8:
  name: "yolo8"
  init_name: "models_weights/default/yolov8m.pt"
  data_yaml: "data/yolo/data.yaml"
  epochs: 15
  seed: 42
  device: "cpu"

yolo11:
  name: "yolo11"
  init_name: "models_weights/default/yolo11m.pt"
  data_yaml: "data/yolo/data.yaml"
  epochs: 15
  seed: 42
  device: "cpu"
  device: "cpu"

faster_rcnn:
  name: "faster_rcnn"
  model_type: "fpn_v2"          # fpn_v2 | v3_large_320_fpn
  optimizer_name: "SGD"         # SGD | AdamW
  epochs: 10
  lr: 0.001
  weight_decay: 0.0005
  seed: 42
  device: "cpu"

ssd:
  name: "ssd"
  model_type: "vgg16"           # vgg16 | v3_large
  optimizer_name: "SGD"         # SGD | AdamW
  epochs: 10
  lr: 0.001
  weight_decay: 0.0005
  seed: 42
  device: "cpu"

detr:
  name: "detr"
  init_subdir: "detr"
  epochs: 5
  optimizer_name: "SGD"         # SGD | AdamW
  lr: 0.001
  weight_decay: 0.0005
  seed: 42
  device: "cpu"
  num_queries: 100

testing:
  device: "cpu"

results:
  save_dir: "results"
  log_interval: 1